yarnPath: ".yarn/releases/yarn-berry.js"
packageExtensions:
  "@jimp/core@*":
    dependencies:
      "regenerator-runtime": "*"
  "@jimp/utils@*":
    dependencies:
      "regenerator-runtime": "*"
  "gatsby-plugin-sass@*":
    peerDependenciesMeta:
      "node-sass":
        "optional": true
