packageExtensions:
  "@jimp/core@*":
    dependencies:
      regenerator-runtime: "*"
  "@jimp/utils@*":
    dependencies:
      regenerator-runtime: "*"
  gatsby-plugin-sass@*:
    peerDependenciesMeta:
      node-sass:
        optional: true

yarnPath: .yarn/releases/yarn-2.4.0.cjs
